version: '3.8'
name: cocoin-batch-10290

services:
  cocoin-batch-10290:
    build:
      context: /data/git/second
      dockerfile: /data/git/second/service-batch/Dockerfile
    container_name: cocoin-batch-10290
    image: kimd0/cocoin-batch:latest
    networks:
      - network_prod
    ports:
      - 10290:10290
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    volumes:
      - batch-10290:/data
    healthcheck:
      test: curl -f http://localhost:10290/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true
volumes:
  batch-10290:
    external: true