version: '3.8'
name: cocoin-batch-10490

services:
  cocoin-batch-10490:
    build:
      context: /data/git/second
      dockerfile: /data/git/second/service-batch/Dockerfile
    container_name: cocoin-batch-10490
    image: kimd0/cocoin-batch:latest
    networks:
      - network_prod
    ports:
      - 10490:10490
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    healthcheck:
      test: curl -f http://localhost:10490/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true