version: '3.8'
name: withfront_prod_backup
services:
  withfront-prod2:
    container_name: withfront_prod2
    image: kimd0/withfront:latest
    networks:
      - network_prod
    ports:
      - 8921:8901
    environment:
      TZ=Asia: Seoul
      USE_PROFILE: prod
    healthcheck:
      test: curl -f http://localhost:8901/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true