version: '3.8'
name: with-socket-dev

services:
  with-socket-dev:
    build:
      context: /data/git/with-socket-dev
      dockerfile: Dockerfile
    container_name: with-socket-dev
    image: kimd0/with-socket-dev:latest
    networks:
      - network_dev
    ports:
      - 9804:9804
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    healthcheck:
      test: curl -f http://localhost:9804/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_dev:
    external: true