version: '3.8'
name: withfile_prod

services:
  withfile-prod:
    container_name: withfile_prod
    image: kimd0/withfile:latest
    networks:
      - network_prod
    ports:
      - 8903:8903
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    volumes:
      - withfile_prod:/home/kimd0
    healthcheck:
      test: curl -f http://localhost:8903/file/health/check || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true
volumes:
  withfile_prod:
    external: true