version: '3.8'
name: server-config-20220

services:
  server-config-20220:
    build:
      context: /data/git/second
      dockerfile: /data/git/second/server-config/Dockerfile
    container_name: server-config-20220
    image: kimd0/server-config:latest
    networks:
      - network_dev
    ports:
      - 20220:10220
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=native
      - USE_EUREKA_URL=http://kimd0.iptime.org:20210/eureka/
    volumes:
      - server-config-20220:/data
    healthcheck:
      test: curl -f http://localhost:20220/actuator/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_dev:
    external: true
volumes:
  server-config-20220:
    external: true