version: '3.8'
name: subuk-b-a-p-0

services:
  subuk-b-a-p-0:
    build:
      context: /data/git/api-b-a
      dockerfile: Dockerfile
    container_name: subuk-b-a-p-0
    image: kimd0/api-b-a:latest
    networks:
      - network_prod
    ports:
      - 12107:10107
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    healthcheck:
      test: curl -f http://localhost:10107/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true