version: '3.8'
name: subuk-b-n-p

services:
  subuk-b-n-p:
    build:
      context: /data/git/subuk-b-n
      dockerfile: Dockerfile
    container_name: subuk-b-n-p
    image: kimd0/subuk-b-n:latest
    networks:
      - network_prod
    ports:
      - 12217:12217
    environment:
      - TZ=Asia/Seoul
    volumes:
      - subuk-b-n-p:/var/log
    healthcheck:
      test: service nginx status || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true
volumes:
  subuk-b-n-p:
    external: true