version: '3.8'
name: jenkins
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/jenkins:/var/jenkins_home
    ports:
      - "8700:8080"
    privileged: true
    user: root