version: '3.8'
name: image-b-a-d-0

services:
  image-b-a-d-0:
    build:
      context: /data/git/image-b-a
      dockerfile: Dockerfile
    container_name: image-b-a-d-0
    image: kimd0/image-b-a:latest
    networks:
      - network_dev
    ports:
      - 20307:20307
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=dev
    volumes:
      - image-b-a-d:/home/kimd0
    healthcheck:
      test: curl -f http://localhost:20307/health/check || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_dev:
    external: true
volumes:
  image-b-a-d:
    external: true