version: '3.8'
name: nginx-b-n-p

services:
  nginx-b-n-p:
    build:
      context: /data/git/nginx-b-n
      dockerfile: Dockerfile
    container_name: nginx-b-n-p
    image: kimd0/nginx-b-n:latest
    networks:
      - network_prod
    ports:
      - 10217:10217
    environment:
      - TZ=Asia/Seoul
    volumes:
      - nginx-b-n-p:/var/log
    healthcheck:
      test: curl -f http://localhost:9910/api/health/check || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true
volumes:
  nginx-b-n-p:
    external: true