version: '3.8'
name: redis-a-r-p

services:
  redis-a-r-p:
    container_name: redis-a-r-p
    image: redis:latest
    networks:
      - network_prod
    ports:
      - 16379:6379
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis-a-r-p:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true
volumes:
  redis-a-r-p:
    external: true