version: '3.8'
name: redis-a-r-d

services:
  redis-a-r-d:
    container_name: redis-a-r-d
    image: redis:latest
    networks:
      - network_dev
    ports:
      - 26379:6379
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis-a-r-d:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_dev:
    external: true
volumes:
  redis-a-r-d:
    external: true