version: '3.8'
name: image-b-a-p-0

services:
  image-b-a-p-0:
    build:
      context: /data/git/image-b-a
      dockerfile: Dockerfile
    container_name: image-b-a-p-0
    image: kimd0/image-b-a:latest
    networks:
      - network_prod
    ports:
      - 10307:10307
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    volumes:
      - image-b-a-p:/home/kimd0
    healthcheck:
      test: curl -f http://localhost:10307/health/check || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true
volumes:
  image-b-a-p:
    external: true