version: '3.8'
name: redis-10480

services:
  redis-10480:
    container_name: redis-10480
    image: redis:latest
    networks:
      - network_prod
    ports:
      - 16379:6379
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis-10480:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    restart: unless-stopped
networks:
  network_prod:
    external: true
volumes:
  redis-10480:
    external: true