version: '3.8'
name: auth_dev

services:
  auth-dev:
    build:
      context: /data/git/auth
      dockerfile: Dockerfile
    container_name: auth_dev
    image: kimd0/auth:latest
    networks:
      - network_dev
    ports:
      - 9801:9801
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=dev
    healthcheck:
      test: curl -f http://localhost:8803/api/auth/health/check || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_dev:
    external: true