version: '3.8'
name: nginx-f-a

services:
  nginx-f-a:
    build:
      context: /data/git/NGINX-F-A
      dockerfile: Dockerfile-nginx-f-a
    container_name: nginx-f-a
    image: kimd0/nginx-f-a:latest
    networks:
      - network_prod
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Seoul
    volumes:
      - nginx-f-a:/var/log
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    healthcheck:
      test: service nginx status || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  network_prod:
    external: true
volumes:
  nginx-f-a:
    external: true