version: '3.8'
name: auth_prod

services:
  auth-prod:
    build:
      context: /data/git/auth
      dockerfile: Dockerfile
    container_name: auth_prod
    image: kimd0/auth:latest
    networks:
      - network_prod
    ports:
      - 9901:9901
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    healthcheck:
      test: curl -f http://localhost:8903/api/auth/health/check || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true