version: '3.8'
name: subuk-f-a-p-1

services:
  subuk-f-a-p-1:
    build:
      context: /data/git/subuk-f-a
      dockerfile: Dockerfile
    container_name: subuk-f-a-p-1
    image: kimd0/subuk-f-a:latest
    networks:
      - network_prod
    ports:
      - 12017:12007
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=pm2:prod
    healthcheck:
      test: curl -f http://localhost:12007 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true