version: '3.8'
name: server-elk-9200

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0  # 모든 네트워크 인터페이스에서 수신
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - cluster.name=docker-cluster
      - node.name=elasticsearch-node

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - network_prod
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_REQUEST_TIMEOUT=120000  # 타임아웃 증가
      - ELASTICSEARCH_PING_TIMEOUT=120000
      - LOGGING_VERBOSE=true  # 디버깅용
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy  # ⚠️ 중요: 헬스체크 기반 의존성
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - network_prod
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
      - PIPELINE_WORKERS=2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - logstash_data:/usr/share/logstash/data
    ports:
      - "5044:5044"
      - "9600:9600"  # API 포트 추가
    depends_on:
      elasticsearch:
        condition: service_healthy  # ⚠️ 중요: 헬스체크 기반 의존성
    networks:
      - network_prod
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9600/_node/stats || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  network_prod:
    external: true

volumes:
  es_data:
    external: true
  kibana_data:
    external: true
  logstash_data:
    external: true