version: '3.8'
name: limepiece-prod

services:
  limepiece-prod-0:
    container_name: limepiece-prod-0
    image: kimd0/limepiece:latest
    networks:
      - network_prod
    ports:
      - 8920:8920
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    healthcheck:
      test: curl -f http://localhost:8901/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  limepiece-prod-1:
    container_name: limepiece-prod-1
    image: kimd0/limepiece:latest
    networks:
      - network_prod
    ports:
      - 8921:8920
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    healthcheck:
      test: curl -f http://localhost:8901/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true