version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-12181
    ports:
      - "12181:2181"
    networks:
      - network_prod
    restart: unless-stopped
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-19092
    ports:
      - "19092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:19092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:12181
    networks:
      - network_prod
    restart: unless-stopped

networks:
  network_prod:
    external: true