version: '3.8'
name: subuk-b-a-d-0

services:
  subuk-b-a-d-0:
    build:
      context: /data/git/api-b-a
      dockerfile: Dockerfile
    container_name: subuk-b-a-d-0
    image: kimd0/api-b-a:latest
    networks:
      - network_dev
    ports:
      - 22107:20107
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=dev
    healthcheck:
      test: curl -f http://localhost:20107/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_dev:
    external: true