version: '3.8'
name: api-b-a-p-2

services:
  api-b-a-p-2:
    build:
      context: /data/git/API-A-A
      dockerfile: Dockerfile
    container_name: api-b-a-p-2
    image: kimd0/api-b-a:latest
    networks:
      - network_prod
    ports:
      - 9912:9910
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    healthcheck:
      test: curl -f http://localhost:9910/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true