version: '3.8'
name: limepiece-f-a-p-2

services:
  limepiece-f-a-p-2:
    build:
      context: /data/git/limepiece-f-a
      dockerfile: Dockerfile
    container_name: limepiece-f-a-p-2
    image: kimd0/limepiece-f-a:latest
    networks:
      - network_prod
    ports:
      - 11027:11007
    environment:
      - TZ=Asia/Seoul
      - USE_PROFILE=prod
    healthcheck:
      test: curl -f http://localhost:11007/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  network_prod:
    external: true